<a href="https://colab.research.google.com/github/GuptaShivam007/Operations_on_Matrices/blob/main/Operations_on_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Adding two matrices

In [2]:
a=np.array([[180,200,220],[24,36,40],[12,18,20]])
b=np.array([[80,90,100],[10,16,20],[8,10,10]])


In [4]:
c=a-b
print(c)

[[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


Matrices Broadcasting

In [5]:
A=np.array([1000,400,1200])
B=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
C=A*B
print(C)

[[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


Multipling Two matrices

In [8]:
np.dot(A,B)

array([34400, 50000, 64400])

Multipling the matrix with the random number

In [9]:
d=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])


In [10]:
75*d

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])